# Workflow to build and release OcrInspector for production
name: Build, Test & Release

# Permissions for the workflow
permissions:
  contents: write

# Trigger workflow on push to the main branch
on:
  push:
    branches:
      - main

# Set environment variables
env:
  artifactStagingDirectory: ${{ github.workspace }}/artifact_staging
  artifactType: 'Production'
  binariesDirectory: ${{ github.workspace }}/binaries
  buildConfiguration: 'Release'
  buildPlatform: 'any cpu'
  projectName: CommandBridge

# Default settings for all run steps
defaults:
  run:
    working-directory: src

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build

  test:
    runs-on: windows-latest
    needs: 
      - build
    if: success()

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
      
    - name: test
      run: dotnet test -l:trx;LogFileName=TestOutput.xml --verbosity normal
      working-directory: src/${{ env.projectName }}.UnitTests

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()      
      with:
        files: |
          src/${{ env.projectName }}.UnitTests/TestResults/*.trx
